version: "3.9"

services:
    DockerCronExample:
        image: chrisbesch/docker_cron_example
        environment:
            - "CRON_TIME=* * * * *"
      
    DockerCron:
        image: chrisbesch/docker_cron
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:rw"
        environment:
            - TZ=Europe/Berlin

